package tugas2.ui;

import tugas2.models.Book;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import tugas2.database.BookDataSource;

public class BookPopup extends javax.swing.JFrame {
	// initialise the model
	private Book book;

	/**
	 * Creates new form BookActivityForm
	 */
	public BookPopup() {
		initComponents();
	}

	/**
	 * Shows an error dialog
	 *
	 * @param message error message
	 */
	private void showError(String message) {
		JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
	}

	/**
	 * Shows success dialog
	 *
	 * @param message success message
	 */
	private void showSuccess(String message) {
		JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
	}

	/**
	 * Helper to set the data
	 *
	 * @param book the `Book` model
	 */
	private void setData(Book book) {
		bookTitle.setText(book.getBookTitle());
		bookAuthor.setText(book.getBookAuthor());
	}

	/**
	 * Sets the book data
	 *
	 * @param book the `Book` model
	 */
	public void setBook(Book book) {
		this.book = book;
		setData(book);
	}

	/**
	 * Validate the empty input
	 *
	 * @return boolean
	 */
	private boolean isInputValid() {
		String judul = bookTitle.getText();
		if (judul.isEmpty()) {
			showError("Judul buku masih kosong");
			return false;
		}
		String author = bookAuthor.getText();
		if (author.isEmpty()) {
			showError("Pengarang buku masih kosong");
			return false;
		}

		return true;
	}

	/**
	 * Sets the data from the input
	 *
	 * @param book the `Book` model
	 */
	private void collectData(Book book) {
		String title = bookTitle.getText();
		String author = bookAuthor.getText();

		book.setBookTitle(title);
		book.setBookAuthor(author);
	}

	/**
	 * Update the data
	 */
	private void saveNewData() {
		book = new Book();
		collectData(book);

		BookDataSource dataSource = new BookDataSource();
		try {
			dataSource.save(book);
			showSuccess("Data buku berhasil disimpan");
		} catch (SQLException e) {
			showError("Data buku gagal disimpan");
			e.printStackTrace();
		}
	}

	/**
	 * Update the data
	 */
	private void updateData() {
		collectData(book);

		BookDataSource datasource = new BookDataSource();
		try {
			datasource.update(book);
			showSuccess("Data buku berhasil diperbaharui");
		} catch (SQLException e) {
			showError("Data buku gagal diperbaharui");
			e.printStackTrace();
		}
	}

	/**
	 * Saves the data to the database
	 */
	private void save() {
		if (!isInputValid()) return;

		// check if we already have a book.
		// If we do, that means we want to update the book data
		// If we don't, we want to add the new book
		if (book != null) {
			updateData();
		} else {
			saveNewData();
		}
	}

	@Override
	public void setTitle(String title) {
		super.setTitle(title); //To change body of generated methods, choose Tools | Templates.
		formTitle.setText(title);
	}


	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		formTitle = new javax.swing.JLabel();
		labelJudul = new javax.swing.JLabel();
		bookTitle = new javax.swing.JTextField();
		bookAuthor = new javax.swing.JTextField();
		labelPengarang = new javax.swing.JLabel();
		submitButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		formTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		formTitle.setText("Form Buku");
		formTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		labelJudul.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
		labelJudul.setText("Judul");

		bookTitle.setText("Masukkan judul buku...");
		bookTitle.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BookTitleActionPerformed(evt);
			}
		});

		bookAuthor.setText("Masukkan judul buku...");
		bookAuthor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BookAuthorActionPerformed(evt);
			}
		});

		labelPengarang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
		labelPengarang.setText("Nama Pengarang");

		submitButton.setText("Submit");
		submitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SubmitButtonActionPerformed(evt);
			}
		});

		cancelButton.setText("Batal");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CancelButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addGap(139, 139, 139)
						.addComponent(formTitle))
					.addGroup(layout.createSequentialGroup()
						.addGap(28, 28, 28)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
							.addGroup(layout.createSequentialGroup()
								.addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(labelJudul)
								.addComponent(bookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(bookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(labelPengarang)))))
				.addContainerGap(29, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addGap(18, 18, 18)
				.addComponent(formTitle)
				.addGap(18, 18, 18)
				.addComponent(labelJudul)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(bookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addComponent(labelPengarang)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(bookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(28, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void BookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTitleActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_JudulBukuActionPerformed

	private void BookAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAuthorActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_PengarangBukuActionPerformed

	private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
		save();
		this.dispose();
	}//GEN-LAST:event_SubmitButtonActionPerformed

	private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
		this.dispose();
	}//GEN-LAST:event_CancelButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(BookPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(BookPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(BookPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(BookPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BookPopup().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cancelButton;
	private javax.swing.JTextField bookTitle;
	private javax.swing.JLabel labelJudul;
	private javax.swing.JLabel labelPengarang;
	private javax.swing.JTextField bookAuthor;
	private javax.swing.JButton submitButton;
	private javax.swing.JLabel formTitle;
	// End of variables declaration//GEN-END:variables
}
