package tugas2.ui;

import tugas2.models.Buku;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import tugas2.database.BukuDataSource;

public class BookActivityForm extends javax.swing.JFrame {

	/**
	 * Creates new form BookActivityForm
	 */
	public BookActivityForm() {
		initComponents();
	}

	private Buku buku;

	private void showError(String message) {
		JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
	}

	private void showSucceed(String message) {
		JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
	}

	private void showOldDataOf(Buku buku) {
		judulBuku.setText(buku.getJudulBuku());
		pengarangBuku.setText(buku.getPengarang());
	}

	public void setBuku(Buku buku) {
		this.buku = buku;
		showOldDataOf(buku);
	}

	private boolean validateAllInput() {
		String judul = judulBuku.getText();
		if (judul.isEmpty()) {
			showError("Judul buku masih kosong");
			return false;
		}
		String pengarang = pengarangBuku.getText();
		if (pengarang.isEmpty()) {
			showError("Pengarang buku masih kosong");
			return false;
		}

		return true;
	}

	private void collectDataFor(Buku buku) {
		String judul = judulBuku.getText();
		String pengarang = pengarangBuku.getText();

		buku.setJudulBuku(judul);
		buku.setPengarang(pengarang);
	}

	private void saveNewData() {
		buku = new Buku();
		collectDataFor(buku);

		BookDataSource datasource = new BookDataSource();
		try {
			datasource.save(buku);
			showSucceed("Data buku berhasil disimpan");
		} catch (SQLException e) {
			showError("Data buku gagal disimpan");
			e.printStackTrace();
		}
	}

	private void updateData() {
		collectDataFor(buku);

		BookDataSource datasource = new BookDataSource();
		try {
			datasource.update(buku);
			showSucceed("Data buku berhasil diperbaharui");
		} catch (SQLException e) {
			showError("Data buku gagal diperbaharui");
			e.printStackTrace();
		}
	}

	private void save() {
		if (!validateAllInput()) {
			return;
		}

		if (buku != null) {
			updateData();
		} else {
			saveNewData();
		}
	}

	@Override
	public void setTitle(String title) {
		super.setTitle(title); //To change body of generated methods, choose Tools | Templates.
		formTitle.setText(title);
	}


	/**
	* This method is called from within the constructor to initialize the
	* form. WARNING: Do NOT modify this code. The content of this method is
	* always regenerated by the Form Editor.
	*/
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		formTitle = new javax.swing.JLabel();
		labelJudul = new javax.swing.JLabel();
		judulBuku = new javax.swing.JTextField();
		pengarangBuku = new javax.swing.JTextField();
		labelPengarang = new javax.swing.JLabel();
		submitButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		formTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		formTitle.setText("Form Buku");
		formTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		labelJudul.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
		labelJudul.setText("Judul");

		judulBuku.setText("Masukkan judul buku...");
		judulBuku.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				JudulBukuActionPerformed(evt);
			}
		});

		pengarangBuku.setText("Masukkan judul buku...");
		pengarangBuku.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				PengarangBukuActionPerformed(evt);
			}
		});

		labelPengarang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
		labelPengarang.setText("Nama Pengarang");

		submitButton.setText("Submit");
		submitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SubmitButtonActionPerformed(evt);
			}
		});

		cancelButton.setText("Batal");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CancelButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addGap(139, 139, 139)
						.addComponent(formTitle))
					.addGroup(layout.createSequentialGroup()
						.addGap(28, 28, 28)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
							.addGroup(layout.createSequentialGroup()
								.addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(labelJudul)
								.addComponent(judulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(pengarangBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(labelPengarang)))))
				.addContainerGap(29, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addGap(18, 18, 18)
				.addComponent(formTitle)
				.addGap(18, 18, 18)
				.addComponent(labelJudul)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(judulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addComponent(labelPengarang)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(pengarangBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(28, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void JudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JudulBukuActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_JudulBukuActionPerformed

	private void PengarangBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengarangBukuActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_PengarangBukuActionPerformed

	private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
		save();
	}//GEN-LAST:event_SubmitButtonActionPerformed

	private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
		dispose();
	}//GEN-LAST:event_CancelButtonActionPerformed

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		*/
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(BookActivityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(BookActivityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(BookActivityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(BookActivityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BookActivityForm().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cancelButton;
	private javax.swing.JTextField judulBuku;
	private javax.swing.JLabel labelJudul;
	private javax.swing.JLabel labelPengarang;
	private javax.swing.JTextField pengarangBuku;
	private javax.swing.JButton submitButton;
	private javax.swing.JLabel formTitle;
	// End of variables declaration//GEN-END:variables
}
