package tugas2.ui;

import tugas2.database.BukuDataSource;
import tugas2.models.Buku;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

public class DataManagerForm extends JFrame {

	/**
	 * Creates new form java
	 */
	public DataManagerForm() {
		initComponents();
		initTableModel();
		loadBookData();
	}

	private DefaultTableModel tableModel;
	private List<Buku> bukuList;

	private void showError(String message) {
		JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
	}

	private void showSucceed(String message) {
		JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
	}

	private void initTableModel() {
		String[] columns = new String[]{"ID Buku", "Judul", "Pengarang"};
		tableModel = new DefaultTableModel(columns, 0);
		tableBarang.setModel(tableModel);
	}

	private void addRowToTableFor(Buku buku) {
		tableModel.addRow(new Object[]{
			buku.getId(),
			buku.getJudulBuku(),
			buku.getPengarang(),
		});
	}

	private void addRowsToTableFor(List<Buku> bookList) {
		for (Buku buku : bookList) {
			addRowToTableFor(buku);
		}
	}

	private void loadBookData() {
		BookDataSource datasource = new BookDataSource();

		if (tableModel.getRowCount() > 0) {
			tableModel.setRowCount(0);
		}

		try {
			bukuList = datasource.findAll();
			addRowsToTableFor(bukuList);
		} catch (SQLException e) {
			showError("Tidak dapat memuat data buku");
			e.printStackTrace();
		}
	}

	private void open(Window activity) {
		activity.setLocationRelativeTo(this);
		activity.setVisible(true);
		activity.addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosed(WindowEvent e) {
				super.windowClosed(e); //To change body of generated methods, choose Tools | Templates.
				loadBookData();
			}
		});
	}

	private void openAddBookActivity() {
		BookActivityForm activity = new BookActivityForm();
		activity.setTitle("Tambah Data Buku");
		open(activity);
	}

	private void openUpdateBookActivity() {
		int selectedRow = tableBarang.getSelectedRow();
		if (selectedRow < 0) {
			showError("Tidak ada data buku terpilih dalam tabel");
			return;
		}

		Buku selectedBuku = bukuList.get(selectedRow);
		BookActivityForm activity = new BookActivityForm();
		activity.setTitle("Update Data Buku");
		activity.setBuku(selectedBuku);
		open(activity);
	}

	private void deleteBook() {
		int selectedRow = tableBarang.getSelectedRow();
		if (selectedRow < 0) {
			showError("Tidak ada data buku terpilih dalam tabel");
			return;
		}

		Buku selectedBook = bukuList.get(selectedRow);
		int confirm = JOptionPane.showConfirmDialog(this, "Yakin Hapus"+selectedBook.getJudulBuku()+" ?");
		if (confirm == JOptionPane.YES_OPTION) {
			BookDataSource datasource = new BookDataSource();
			try {
				datasource.delete(selectedBook);
				tableModel.removeRow(selectedRow);
				bukuList.remove(selectedBook);
				showSucceed("Data buku berhasil dihapus");
			} catch (SQLException e) {
				showSucceed("Data buku gagal dihapus");
				e.printStackTrace();
			}
		}
	}


	/**
	* This method is called from within the constructor to initialize the
	* form. WARNING: Do NOT modify this code. The content of this method is
	* always regenerated by the Form Editor.
	*/
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		closeButton = new javax.swing.JButton();
		deleteButton = new javax.swing.JButton();
		updateButton = new javax.swing.JButton();
		addButton = new javax.swing.JButton();
		dataScrollPane = new javax.swing.JScrollPane();
		tableBarang = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Data Manager Buku");

		jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel1.setText("Data Manager Buku");

		closeButton.setText("Tutup");
		closeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				closeButtonActionPerformed(evt);
			}
		});

		deleteButton.setText("Hapus");
		deleteButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteButtonActionPerformed(evt);
			}
		});

		updateButton.setText("Update");
		updateButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				updateButtonActionPerformed(evt);
			}
		});

		addButton.setText("Tambah");
		addButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addButtonActionPerformed(evt);
			}
		});

		dataScrollPane.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

		tableBarang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		tableBarang.setModel(new javax.swing.table.DefaultTableModel(
			new Object [][] {
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null}
			},
			new String [] {
				"Title 1", "Title 2", "Title 3", "Title 4"
			}
		));
		dataScrollPane.setViewportView(tableBarang);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
				.addGap(14, 14, 14)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
					.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
						.addComponent(addButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(updateButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(deleteButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(closeButton))
					.addComponent(dataScrollPane))
				.addGap(18, 18, 18))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addGap(15, 15, 15)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(jLabel1))
				.addGap(18, 18, 18)
				.addComponent(dataScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(16, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
		System.exit(0);
	}//GEN-LAST:event_closeButtonActionPerformed

	private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
		deleteBook();
	}//GEN-LAST:event_deleteButtonActionPerformed

	private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
		openUpdateBookActivity();
	}//GEN-LAST:event_updateButtonActionPerformed

	private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
		openAddBookActivity();
	}//GEN-LAST:event_addButtonActionPerformed

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		*/
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DataManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DataManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DataManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DataManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DataManagerForm().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addButton;
	private javax.swing.JButton closeButton;
	private javax.swing.JScrollPane dataScrollPane;
	private javax.swing.JButton deleteButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTable tableBarang;
	private javax.swing.JButton updateButton;
	// End of variables declaration//GEN-END:variables
}
