/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kasir;

import javax.swing.JFrame;
import com.formdev.flatlaf.FlatDarkLaf;

import kasir.ui.Login;

public class App {
    public static void main(String[] args) {
		FlatDarkLaf.install();

		JFrame loginScreen = new Login();
		loginScreen.setVisible(true);
		loginScreen.setResizable(false);
    }
}
