package kasir.ui;

import java.util.List;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

import kasir.helpers.FormatRupiah;
import kasir.helpers.OrderTable;
import kasir.helpers.Popup;
import kasir.models.User;

public class Kasir extends javax.swing.JFrame {
	private OrderTable tableData = new OrderTable();
	private DefaultTableModel foodTableModel;
	private long price = 0, amount = 0;

	/**
	 * Creates new form Order
	 */
	public Kasir() {
	}
	public Kasir(User currentUser) {
		// center the window
		this.setLocationRelativeTo(null);

		// override the close handler
		this.addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent e) {
				if (foodTable.getRowCount() != 0) {
					JOptionPane.showMessageDialog(null, "Anda masih punya item tersisa!");
					return;
				}
				System.exit(0);
			}
		});

		// init the component and populate it with data
		initComponents();
		initTableModel();

		// hide back button if the current user is not an admin
		if (currentUser.getLevelID() != 1) {
			backButton.setVisible(false);
		}

		payAmountField.getDocument().addDocumentListener(new DocumentListener() {
			public void changedUpdate(DocumentEvent e) {
				setExchangeAmount();
			}
			public void removeUpdate(DocumentEvent e) {
				setExchangeAmount();
			}
			public void insertUpdate(DocumentEvent e) {
				setExchangeAmount();
			}
		});
	}

	private void setExchangeAmount() {
		// don't do anything if we don't have any items
		if (totalPriceField.getText().isEmpty()) {
			return;
		}

		String priceNumber = totalPriceField.getText().replaceAll("[a-zA-Z\\.\\s]", "");
		long totalPrice = Long.parseLong(priceNumber);
		long payAmount = Long.parseLong(payAmountField.getText());
		long exchange = totalPrice - payAmount;
		if (exchange < 0 && String.valueOf(exchange) != "") {
			exchangeField.setText(("Rp. " + FormatRupiah.format(exchange)).replace("-", ""));
		} else {
			exchangeField.setText("Pembayaran belum cukup");
		}
	}

	/**
	 * Set the desired table model
	 */
	private void initTableModel() {
		String[] columns = new String[]{
			"ID", "Nama Masakan", "Jumlah Pesanan", "Harga"
		};
		foodTableModel = new DefaultTableModel(columns, 0) {
			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return false;
			}
		};
		foodTable.setModel(foodTableModel);
		foodTable.getTableHeader().setReorderingAllowed(false); // prevent from table re-ordering
	}

	/**
	 * Set the table data
	 */
	public void setTableData(List<List<Object>> data) {
		// populate the table
		for (List<Object> row : data) {
			foodTableModel.addRow(new Object[] {
				row.get(0),
				row.get(1),
				row.get(2),
				"Rp. " + FormatRupiah.format((long)row.get(3)),
			});
		}

		// takes care of the details
		for (List<Object> row : data) amount += (long)row.get(2);
		foodAmountField.setText(String.valueOf(amount));

		for (List<Object> row : data) price += (long)row.get(3);
		totalPriceField.setText("Rp. " + FormatRupiah.format(price));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		scrollPane = new javax.swing.JScrollPane();
		foodTable = new javax.swing.JTable();
		foodAmountField = new javax.swing.JTextField();
		foodAmountLabel = new javax.swing.JLabel();
		totalPriceLabel = new javax.swing.JLabel();
		totalPriceField = new javax.swing.JTextField();
		payAmountField = new javax.swing.JTextField();
		payAmountLabel = new javax.swing.JLabel();
		exchangeField = new javax.swing.JTextField();
		exchangeLabel = new javax.swing.JLabel();
		addItemButton = new javax.swing.JButton();
		removeButton = new javax.swing.JButton();
		orderTitle = new javax.swing.JLabel();
		logoutButton = new javax.swing.JButton();
		confirmButton = new javax.swing.JButton();
		customerNameField = new javax.swing.JTextField();
		customerNameLabel = new javax.swing.JLabel();
		backButton = new javax.swing.JButton();

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 100, Short.MAX_VALUE)
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 100, Short.MAX_VALUE)
		);

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

		scrollPane.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

		foodTable.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
		foodTable.setModel(new javax.swing.table.DefaultTableModel(
			new Object [][] {

			},
			new String [] {
				"ID", "Nama Masakan", "Jumlah Pesanan", "Harga"
			}
		) {
				Class[] types = new Class [] {
					java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class
				};
				boolean[] canEdit = new boolean [] {
					false, false, false, false
				};

				public Class getColumnClass(int columnIndex) {
					return types [columnIndex];
				}

				public boolean isCellEditable(int rowIndex, int columnIndex) {
					return canEdit [columnIndex];
				}
			});
		scrollPane.setViewportView(foodTable);

		foodAmountField.setEditable(false);

		foodAmountLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		foodAmountLabel.setText("Jumlah Makanan");

		totalPriceLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		totalPriceLabel.setText("Total Harga");

		totalPriceField.setEditable(false);

		payAmountLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		payAmountLabel.setText("Jumlah Bayar");

		exchangeField.setEditable(false);

		exchangeLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		exchangeLabel.setText("Kembalian");

		addItemButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		addItemButton.setText("Tambah Item");
		addItemButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addItemButtonActionPerformed(evt);
			}
		});

		removeButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		removeButton.setText("Hapus Item");
		removeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				removeButtonActionPerformed(evt);
			}
		});

		orderTitle.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		orderTitle.setText("Order Masakan");

		logoutButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
		logoutButton.setText("Logout");
		logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		logoutButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				logoutButtonActionPerformed(evt);
			}
		});

		confirmButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		confirmButton.setText("Konfirmasi Order");
		confirmButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				confirmButtonActionPerformed(evt);
			}
		});

		customerNameLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		customerNameLabel.setText("Nomor Meja");

		backButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
		backButton.setText("Kembali");
		backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		backButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
				.addContainerGap(21, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
					.addGroup(layout.createSequentialGroup()
						.addComponent(logoutButton)
						.addGap(234, 234, 234)
						.addComponent(orderTitle)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
							.addComponent(customerNameLabel)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(backButton)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
									.addComponent(foodAmountField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
									.addComponent(foodAmountLabel)
									.addComponent(totalPriceLabel)
									.addComponent(totalPriceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
									.addComponent(payAmountField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
									.addComponent(payAmountLabel)
									.addComponent(exchangeLabel)
									.addComponent(exchangeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
									.addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(addItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(customerNameField))))
						.addGap(18, 18, 18))))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
				.addGap(17, 17, 17)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(orderTitle)
					.addComponent(logoutButton)
					.addComponent(backButton))
				.addGap(35, 35, 35)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
					.addGroup(layout.createSequentialGroup()
						.addComponent(customerNameLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(foodAmountLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(foodAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(12, 12, 12)
						.addComponent(totalPriceLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(totalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(payAmountLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(payAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(exchangeLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(exchangeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(addItemButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(removeButton)
						.addGap(13, 13, 13)
						.addComponent(confirmButton))
					.addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
				.addContainerGap(19, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
		int row = foodTable.getSelectedRow();

		String id = foodTable.getValueAt(row, 0).toString();
		long amount = Long.parseLong(foodTable.getValueAt(row, 2).toString());

		FoodSource foodSource = new FoodSource();

		try {
			// we need to do this because we want the detail of the selected item
			// from the database so we can calculate how many stocks there are
			Food filter = new Food();
			filter.setFoodID(id);
			Food food = foodSource.find(filter);

			// add the existing stock with the selected stock. What we want is
			// if we have 2 items in the database and 1 item in the foodTable
			// we want to update the one in the database to 3 items
			food.setStock(food.getStock() + amount);
			foodSource.update(food);

			// remove the item from the table
			foodTableModel.removeRow(row);

			JOptionPane.showMessageDialog(this, "Berhasil menghapus data!");
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(this, "Gagal menghapus data!");
			ex.printStackTrace();
		}
	}//GEN-LAST:event_removeButtonActionPerformed

	private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
		// don't let user logout if they have an item on the table
		if (foodTable.getRowCount() != 0) {
			JOptionPane.showMessageDialog(null, "Anda masih punya item tersisa!");
			return;
		}
		Popup.<Login>open(new Login(), "Login Aplikasi Kasir");
		this.dispose();
	}//GEN-LAST:event_logoutButtonActionPerformed

	private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_confirmButtonActionPerformed

	private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
		Popup.<KasirPopup>open(new KasirPopup(tableData, this), "Tambah Item");
	}//GEN-LAST:event_addItemButtonActionPerformed

	private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_backButtonActionPerformed

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Kasir().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addItemButton;
	private javax.swing.JButton backButton;
	private javax.swing.JButton cancelButton;
	private javax.swing.JButton confirmButton;
	private javax.swing.JTextField customerNameField;
	private javax.swing.JLabel customerNameLabel;
	private javax.swing.JTextField exchangeField;
	private javax.swing.JLabel exchangeLabel;
	private javax.swing.JTextField foodAmountField;
	private javax.swing.JLabel foodAmountLabel;
	private javax.swing.JTable foodTable;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane scrollPane;
	private javax.swing.JButton logoutButton;
	private javax.swing.JLabel orderTitle;
	private javax.swing.JTextField payAmountField;
	private javax.swing.JLabel payAmountLabel;
	private javax.swing.JTextField totalPriceField;
	private javax.swing.JLabel totalPriceLabel;
	// End of variables declaration//GEN-END:variables
}
