package kasir.ui;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import kasir.controllers.MasakanSource;
import kasir.models.Masakan;

public class MenuPopup extends javax.swing.JFrame {
	private MenuManager parentWindow;
	private Masakan currentFood;
	private String mode = "add";

	/**
	 * Creates new form MenuPopup
	 */
	public MenuPopup() {
	}
	public MenuPopup(MenuManager parent) {
		this.setLocationRelativeTo(null);
		initComponents();
		parentWindow = parent;
	}
	public MenuPopup(MenuManager parent, Masakan food) {
		this.setLocationRelativeTo(null);
		initComponents();
		parentWindow = parent;
		currentFood = food;
		mode = "edit";

		populateData();
	}

	private void populateData() {
		idField.setText(currentFood.getFoodID());
		nameField.setText(currentFood.getName());
		stockField.setText(String.valueOf(currentFood.getStock()));
		priceField.setText(String.valueOf(currentFood.getPrice()));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		windowTitle = new javax.swing.JLabel();
		idLabel = new javax.swing.JLabel();
		idField = new javax.swing.JTextField();
		nameField = new javax.swing.JTextField();
		nameLabel = new javax.swing.JLabel();
		priceField = new javax.swing.JTextField();
		priceLabel = new javax.swing.JLabel();
		stockField = new javax.swing.JTextField();
		stockLabel = new javax.swing.JLabel();
		saveButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		windowTitle.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		windowTitle.setText("Tambah Menu");

		idLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		idLabel.setText("ID Masakan");

		idField.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

		nameField.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

		nameLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		nameLabel.setText("Nama Masakan");

		priceField.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

		priceLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		priceLabel.setText("Harga Masakan");

		stockField.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

		stockLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		stockLabel.setText("Stok Masakan");

		saveButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		saveButton.setText("Simpan");
		saveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveButtonActionPerformed(evt);
			}
		});

		cancelButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		cancelButton.setText("Batal");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addGap(16, 16, 16)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
							.addComponent(idLabel)
							.addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addComponent(nameLabel))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
							.addGroup(layout.createSequentialGroup()
								.addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(saveButton))
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(priceLabel)
								.addComponent(stockField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
								.addComponent(stockLabel)
								.addComponent(priceField))))
					.addGroup(layout.createSequentialGroup()
						.addGap(143, 143, 143)
						.addComponent(windowTitle)))
				.addContainerGap(21, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addGap(16, 16, 16)
				.addComponent(windowTitle)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
					.addGroup(layout.createSequentialGroup()
						.addComponent(idLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(nameLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup()
						.addComponent(priceLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(stockLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(stockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addGap(29, 29, 29)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(saveButton)
					.addComponent(cancelButton))
				.addContainerGap(23, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
		this.dispose();
	}//GEN-LAST:event_cancelButtonActionPerformed

	private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
		String id = idField.getText();
		String name = nameField.getText();
		String stock = stockField.getText();
		String price = priceField.getText().replaceAll("[a-zA-Z\\.\\s]", "");

		if (id.isEmpty() || name.isEmpty() || stock.isEmpty() || price.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
			return;
		}

		try {
			MasakanSource foodSource = new MasakanSource();

			// set the current food details
			currentFood.setFoodID(id);
			currentFood.setName(name);
			currentFood.setStock(Long.parseLong(stock));
			currentFood.setPrice(Long.parseLong(price));

			// do action based on current `popup-mode`
			if (mode == "add") {
				foodSource.save(currentFood);
			} else {
				foodSource.update(currentFood);
			}

			// we need this here to refresh the parent table view
			parentWindow.populateData();

			JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(this, "Data gagal disimpan!");
			ex.printStackTrace();
		}

	}//GEN-LAST:event_saveButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MenuPopup().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cancelButton;
	private javax.swing.JTextField idField;
	private javax.swing.JLabel idLabel;
	private javax.swing.JTextField nameField;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JTextField priceField;
	private javax.swing.JLabel priceLabel;
	private javax.swing.JButton saveButton;
	private javax.swing.JTextField stockField;
	private javax.swing.JLabel stockLabel;
	private javax.swing.JLabel windowTitle;
	// End of variables declaration//GEN-END:variables
}
