package kasir.ui;

import java.sql.SQLException;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import kasir.controllers.FoodSource;
import kasir.helpers.FormatRupiah;
import kasir.helpers.Popup;
import kasir.models.Food;

public class MenuManager extends javax.swing.JFrame {
	private DefaultTableModel foodTableModel;
	private Admin parentWindow;
	private Food currentFood = new Food();

	/**
	 * Creates new form MenuManagement
	 */
	public MenuManager() {
	}
	public MenuManager(Admin parent) {
		this.setLocationRelativeTo(null);
		initComponents();
		initTableModel();
		populateData();
		attachOnSelectionEvent();
		parentWindow = parent;
	}

	/**
	 * Set the desired table model
	 */
	private void initTableModel() {
		String[] columns = new String[]{
			"ID", "Nama Masakan", "Stok", "Harga", "Status"
		};
		foodTableModel = new DefaultTableModel(columns, 0) {
			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return false;
			}
		};
		foodTable.setModel(foodTableModel);
		foodTable.getTableHeader().setReorderingAllowed(false); // prevent from table re-ordering
	}

	/**
	 * Populate table with initial data from the database
	 */
	public void populateData() {
		// always reset the table first before filling it
		foodTable.clearSelection();
		foodTableModel.setRowCount(0);
		foodTable.revalidate();

		try {
			List<Food> foods = new FoodSource().findAll();

			for (Food food : foods) {
				foodTableModel.addRow(new Object[] {
					food.getFoodID(),
					food.getName(),
					food.getStock(),
					FormatRupiah.format(food.getPrice()),
					food.getStatus(),
				});
			}
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(null, "Tidak dapat memuat data!");
			ex.printStackTrace();
		}
	}

	private void attachOnSelectionEvent() {
		foodTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent evt) {
				int selectedRow = foodTable.getSelectedRow();

				// we need to guard this here because when the row is cleared,
				// nothing gets selected
				if (selectedRow == -1) return;

				// set details for text fields
				idField.setText(foodTable.getValueAt(selectedRow, 0).toString());
				foodNameField.setText(foodTable.getValueAt(selectedRow, 1).toString());
				foodStockField.setText(foodTable.getValueAt(selectedRow, 2).toString());
				priceField.setText(foodTable.getValueAt(selectedRow, 3).toString());

				// change the current user
				currentFood.setFoodID(foodTable.getValueAt(selectedRow, 0).toString());
				currentFood.setName(foodTable.getValueAt(selectedRow, 1).toString());
				currentFood.setStock(Long.parseLong(foodTable.getValueAt(selectedRow, 2).toString()));
				String priceNumber = FormatRupiah.normalise(foodTable.getValueAt(selectedRow, 3).toString());
				currentFood.setPrice(Long.parseLong(priceNumber));
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		windowTitle = new javax.swing.JLabel();
		deleteButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		foodTable = new javax.swing.JTable();
		priceField = new javax.swing.JTextField();
		foodStockField = new javax.swing.JTextField();
		foodNameField = new javax.swing.JTextField();
		foodStockLabel = new javax.swing.JLabel();
		priceLabel = new javax.swing.JLabel();
		foodNameLabel = new javax.swing.JLabel();
		idField = new javax.swing.JTextField();
		idLabel = new javax.swing.JLabel();
		backButton = new javax.swing.JButton();
		logoutButton = new javax.swing.JButton();
		editButton = new javax.swing.JButton();
		addButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		windowTitle.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		windowTitle.setText("Manajemen Menu");

		deleteButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		deleteButton.setText("Hapus Item");
		deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		deleteButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteButtonActionPerformed(evt);
			}
		});

		jScrollPane1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

		foodTable.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
		foodTable.setModel(new javax.swing.table.DefaultTableModel(
			new Object [][] {
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null}
			},
			new String [] {
				"ID", "Nama Masakan", "Stok", "Harga Satuan"
			}
		) {
				Class[] types = new Class [] {
					java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class
				};
				boolean[] canEdit = new boolean [] {
					false, false, false, false
				};

				public Class getColumnClass(int columnIndex) {
					return types [columnIndex];
				}

				public boolean isCellEditable(int rowIndex, int columnIndex) {
					return canEdit [columnIndex];
				}
			});
		jScrollPane1.setViewportView(foodTable);

		priceField.setEditable(false);

		foodStockField.setEditable(false);

		foodNameField.setEditable(false);

		foodStockLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		foodStockLabel.setText("Stok Masakan");

		priceLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		priceLabel.setText("Harga Satuan");

		foodNameLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		foodNameLabel.setText("Nama Masakan");

		idField.setEditable(false);

		idLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		idLabel.setText("ID Masakan");

		backButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
		backButton.setText("Kembali");
		backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		backButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backButtonActionPerformed(evt);
			}
		});

		logoutButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
		logoutButton.setText("Logout");
		logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		logoutButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				logoutButtonActionPerformed(evt);
			}
		});

		editButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		editButton.setText("Edit Item");
		backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		editButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				editButtonActionPerformed(evt);
			}
		});

		addButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		addButton.setText("Tambah Item");
		addButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addContainerGap(16, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18))
					.addGroup(layout.createSequentialGroup()
						.addComponent(logoutButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(windowTitle)
						.addGap(81, 81, 81)))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
					.addComponent(idField, javax.swing.GroupLayout.Alignment.TRAILING)
					.addComponent(idLabel)
					.addComponent(foodNameLabel)
					.addComponent(foodNameField, javax.swing.GroupLayout.Alignment.TRAILING)
					.addComponent(foodStockField, javax.swing.GroupLayout.Alignment.TRAILING)
					.addComponent(foodStockLabel)
					.addComponent(priceLabel)
					.addComponent(priceField, javax.swing.GroupLayout.Alignment.TRAILING)
					.addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
					.addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING))
				.addGap(14, 14, 14))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addGap(17, 17, 17)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
					.addComponent(windowTitle)
					.addComponent(logoutButton)
					.addComponent(backButton))
				.addGap(30, 30, 30)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
					.addGroup(layout.createSequentialGroup()
						.addComponent(idLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(foodNameLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(foodNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(foodStockLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(foodStockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(priceLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(editButton)
						.addGap(18, 18, 18)
						.addComponent(addButton)
						.addGap(18, 18, 18)
						.addComponent(deleteButton))
					.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
				.addContainerGap(20, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_deleteButtonActionPerformed

	private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {
		Popup.<MenuPopup>open(new MenuPopup(this), "Tambah Menu");
	}

	private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {
		if (foodTable.getSelectedRow() == -1) {
			JOptionPane.showMessageDialog(this, "Tidak ada makanan yang dipilih!");
			return;
		}

		Popup.<MenuPopup>open(new MenuPopup(this, currentFood), "Edit Menu");
	}


	private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
		Popup.<Admin>open(new Admin(), "Halaman Admin");
		this.dispose();
	}//GEN-LAST:event_backButtonActionPerformed

	private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
		Popup.<Login>open(new Login(), "Login Aplikasi Kasir");
		this.dispose();
		parentWindow.dispose();
	}//GEN-LAST:event_logoutButtonActionPerformed

	/**
	 * @param args the command line arguments
	*/
	public static void main(String args[]) {
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MenuManager().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addButton;
	private javax.swing.JButton backButton;
	private javax.swing.JButton deleteButton;
	private javax.swing.JButton editButton;
	private javax.swing.JTextField foodNameField;
	private javax.swing.JLabel foodNameLabel;
	private javax.swing.JTextField foodStockField;
	private javax.swing.JLabel foodStockLabel;
	private javax.swing.JTable foodTable;
	private javax.swing.JTextField idField;
	private javax.swing.JLabel idLabel;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton logoutButton;
	private javax.swing.JTextField priceField;
	private javax.swing.JLabel priceLabel;
	private javax.swing.JLabel windowTitle;
	// End of variables declaration//GEN-END:variables
}
