package kasir.ui;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import kasir.ui.OrderPopup;

/**
 *
 * @author elianiva
 */
public class Order extends javax.swing.JFrame {

	/**
	 * Creates new form Order
	 */
	public Order() {
		initComponents();
		this.setLocationRelativeTo(null); // center the window
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		foodTable = new javax.swing.JTable();
		foodAmountField = new javax.swing.JTextField();
		foodAmountLabel = new javax.swing.JLabel();
		totalPriceLabel = new javax.swing.JLabel();
		totalPriceField = new javax.swing.JTextField();
		payAmountField = new javax.swing.JTextField();
		payAmountLabel = new javax.swing.JLabel();
		exchangeField = new javax.swing.JTextField();
		exchangeLabel = new javax.swing.JLabel();
		addItemButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();
		orderTitle = new javax.swing.JLabel();
		logoutButton = new javax.swing.JButton();
		confirmButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jScrollPane1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

		foodTable.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
		foodTable.setModel(new javax.swing.table.DefaultTableModel(
			new Object [][] {
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null},
				{null, null, null, null}
			},
			new String [] {
				"ID", "Nama Masakan", "Jumlah Pesanan", "Harga"
			}
		) {
				Class[] types = new Class [] {
					java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class
				};
				boolean[] canEdit = new boolean [] {
					false, false, false, false
				};

				public Class getColumnClass(int columnIndex) {
					return types [columnIndex];
				}

				public boolean isCellEditable(int rowIndex, int columnIndex) {
					return canEdit [columnIndex];
				}
			});
		jScrollPane1.setViewportView(foodTable);

		foodAmountLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		foodAmountLabel.setText("Jumlah Makanan");

		totalPriceLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		totalPriceLabel.setText("Total Harga");

		totalPriceField.setEditable(false);

		payAmountLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		payAmountLabel.setText("Jumlah Bayar");

		exchangeField.setEditable(false);

		exchangeLabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		exchangeLabel.setText("Kembalian");

		addItemButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		addItemButton.setText("Tambah Item");
		addItemButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addItemButtonActionPerformed(evt);
			}
		});

		cancelButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		cancelButton.setText("Batalkan");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		orderTitle.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		orderTitle.setText("Order Masakan");

		logoutButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
		logoutButton.setText("Logout");
		logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		logoutButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				logoutButtonActionPerformed(evt);
			}
		});

		confirmButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
		confirmButton.setText("Konfirmasi Order");
		confirmButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				confirmButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
				.addContainerGap(21, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
					.addGroup(layout.createSequentialGroup()
						.addComponent(logoutButton)
						.addGap(234, 234, 234)
						.addComponent(orderTitle)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
							.addComponent(foodAmountField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
							.addComponent(foodAmountLabel)
							.addComponent(totalPriceLabel)
							.addComponent(totalPriceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
							.addComponent(payAmountField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
							.addComponent(payAmountLabel)
							.addComponent(exchangeLabel)
							.addComponent(exchangeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
							.addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(addItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(18, 18, 18))))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
				.addGap(17, 17, 17)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(orderTitle)
					.addComponent(logoutButton))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addComponent(foodAmountLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(foodAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(totalPriceLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(totalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(payAmountLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(payAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(exchangeLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(exchangeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(addItemButton)
						.addGap(13, 13, 13)
						.addComponent(confirmButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(cancelButton))
					.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(22, 22, 22))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_cancelButtonActionPerformed

	private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
		Login loginScreen = new Login();
		loginScreen.setTitle("Login Aplikasi Kasir");
		loginScreen.setVisible(true);
		loginScreen.setResizable(false);
		loginScreen.setLocationRelativeTo(null); // center the window
		this.dispose();
	}//GEN-LAST:event_logoutButtonActionPerformed

	private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_confirmButtonActionPerformed

	private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
		OrderPopup orderPopupWindow = new OrderPopup();
		orderPopupWindow.setVisible(true);
		orderPopupWindow.setTitle("Tambah Item");
		orderPopupWindow.setResizable(false);
	}//GEN-LAST:event_addItemButtonActionPerformed

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		// use better look and feel
		try {
			UIManager.setLookAndFeel(new FlatLightLaf());
		} catch (UnsupportedLookAndFeelException e){
			System.out.println(e);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Order().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addItemButton;
	private javax.swing.JButton cancelButton;
	private javax.swing.JButton confirmButton;
	private javax.swing.JTextField exchangeField;
	private javax.swing.JLabel exchangeLabel;
	private javax.swing.JTextField foodAmountField;
	private javax.swing.JLabel foodAmountLabel;
	private javax.swing.JTable foodTable;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton logoutButton;
	private javax.swing.JLabel orderTitle;
	private javax.swing.JTextField payAmountField;
	private javax.swing.JLabel payAmountLabel;
	private javax.swing.JTextField totalPriceField;
	private javax.swing.JLabel totalPriceLabel;
	// End of variables declaration//GEN-END:variables
}
